# https://butterfly.js.org/posts/4aa8abbe/

# 主页subtitle
subtitle:
  enable: true
  # 打字效果
  effect: false
  # 循环或者只打字一次
  loop: false
  # source调用第三方服务
  # source: false 关闭调用
  # source: 1  调用搏天api的随机语录（简体） https://api.btstu.cn/
  # source: 2  调用一言网的一句话（简体） https://hitokoto.cn/
  # source: 3  调用一句网（简体） http://yijuzhan.com/
  # source: 4  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: false
  # 如果有英文逗号' , ',请使用转义字元 &#44;
  # 如果有英文双引号' " ',请使用转义字元 &quot;
  # 开头不允许转义字元，如需要，请把整个句子用双引号包住
  # 例如 ”&quotNever put off till tomorrow what you can do today&quot"
  # 如果关闭打字效果，subtitle只会显示sub的第一行文字
  sub:
    - Nothing is impossible for a willing heart
    # - Never put off till tomorrow what you can do today



# 顶部菜单
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  GitHub: https://github.com/yangzx1282 || fas fa-folder-open
  # List || fas fa-list:
  #   - Music || /music/ || fas fa-music
  #   - Movie || /movies/ || fas fa-video
  Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart

# 顶部图
# index_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)' # 首页
index_img: './static/bg_sheep.jpg' # 首页
default_top_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)' # 默认的 top_img，当页面的 top_img 没有配置时，会显示 default_top_img
footer_bg: true # footer 是否显示图片背景(与top_img一致)
archive_img: 'linear-gradient(-90deg, #e4afcb 0%, #b8cbb8 0%, #b8cbb8 0%, #e2c58b 30%, #c2ce9c 64%, #7edbdc 100%)'
tag_img: 'linear-gradient(to right, #3b41c5 0%, #a981bb 49%, #ffc8a9 100%)' # tag 子页面 的 默认 top_img
category_img: 'linear-gradient(to right, #ff9569 0%, #e92758 100%)'
# tag_per_img：# 设置每个单独的分类
#   java: https://xxxxxx.png
#   python: ddddddd.png

# 主题色
theme_color:
  enable: true
  main: "#0DD16F"
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#99A9BF"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00C4B6"
  blockquote_padding_color: "#49B1F5"
  blockquote_background_color: "#49B1F5"
# 网站背景色
# 图片格式 url(http://xxxxxx.com/xxx.jpg)
# 颜色（HEX值/RGB值/顔色单词/渐变色)
# 留空 不显示背景
background:

# 底部设置
footer:
  owner:
    enable: true
    since: 2020
  custom_text: Copyright © 2020-2021 <a href="https://www.xiaosm.cn">WWW.XIAOSM.CN</a><br/><a href="https://beian.miit.gov.cn/"><span>湘ICP备18023752号-1</span></a>
  ICP:
    enable: true
    url: https://beian.miit.gov.cn/
    text: 湘ICP备18023752号-1
    icon: ''



# 头像
avatar:
  img: https://q1.qlogo.cn/g?b=qq&nk=1282381264&s=640
  effect: true # 头像会一直转圈
# 图片描述
photofigcaption: true 
# copy settings
# copyright: Add the copyright information after copied content (复製的内容后面加上版权信息)
copy:
  enable: true  # 是否开启网站复製权限
  copyright:
    enable: true  # 是否开启复製版权信息添加
    limit_count: 100  # 字数



# 美化页面显示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
# 页面锚点
# when you scroll in post , the url will update according to header id.
anchor:
  button:
    enable: true
    always_show: false
    icon: # the unicode value of Font Awesome icon, such as '\3423'
  auto_update: true # when you scroll in post, the URL will update according to header id.

# 文章摘要
index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config
# 文章封面
cover:
  # 是否显示文章封面
  index_enable: false
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover:
    - https://backiee.com/static/wpdb/wallpapers/1000x563/217260.jpg
    - https://backiee.com/static/wpdb/wallpapers/1000x563/171423.jpg
    - https://backiee.com/static/wpdb/wallpapers/1000x563/157681.jpg
    - https://backiee.com/static/wpdb/wallpapers/1000x563/305475.jpg

# 代码样式
highlight_theme: mac
# 可配置代码高度限制，超出的部分会隐藏，并显示展开按钮
highlight_height_limit: false # 单位是 px，直接添加数字，如 200

# 图片放大
# fancybox http://fancyapps.com/fancybox/3/
fancybox: true
# 评论
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Utterances/Facebook Comments
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
# 评论插件
valine:
  appId: mhN0GGeSEH5QOnIMjTqLq8FT-gzGzoHsz  # leancloud application app id
  appKey: xgc5iSYGnkEVKNELhsRYXNNt # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  placeholder: 记得留下你的昵称和邮箱....可以快速收到回复，昵称位置可以输入QQ号，我们会一键填入 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info (nick/mail/link)
  recordIP: false # Record reviewer IP
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: /image/comment_bg.png # valine background
  emojiCDN: # emoji CDN
  enableQQ: true # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: nick,mail # required fields (nick/mail)
  option:

# 百度收录
# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification: 9yxyDeX7XspXAHuH
# 百度统计 https://tongji.baidu.com/web/welcome/login
baidu_analytics: e5c558916c618f835fdab015b2dafd4f

# 数学公式
katex:
  enable: true
  # true 表示每一页都加载katex.js
  # false 需要时加载，须在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true

# https://mermaid-js.github.io/mermaid/#/
mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme: default

# 全站访问统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
runtimeshow:
  enable: true
  publish_date: 1/1/2020 00:00:00  
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间

# A simple 404 page
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: 

