name: Build # action name

on:
  push:
    branches:
      - master # 当 master 分支发生 push 请求时执行

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push To gh-pages
        # https://github.com/peaceiris/actions-gh-pages/tree/v3/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 无需配置，由 github 提供
          publish_dir: ./public                      # 将指定目录下的文件 push 至 gh-pages
          commit_message: ${{ github.event.head_commit.message }}