name: Deploy

on:
  workflow_run:
    workflows: [Build]
    branches: [master]
    types:
      - completed

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout    
        uses: actions/checkout@v3  # 这里使用了github官方提供的action,checkout项目到虚拟机上
        with:
          ref: gh-pages

      - name: Deploy file to tencent
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: '${{ secrets.SERVER_USER }}'  # ssh user name
          server: '${{ secrets.SERVER_HOST }}'  # 引用之前创建好的secret
          ssh_private_key: ${{ secrets.PRIVITE_KEY }}  # 引用之前创建好的secret
          local_path: './*'  # 对应我们项目build的文件夹路径
          remote_path: '${{ secrets.TARGET_PATH }}' # 远程服务器路径