name: Deploy

on:
  push:
    branches:
      - gh-pages # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout    
        uses: actions/checkout@v2    #这里使用了github官方提供的action,checkout项目到虚拟机上

      # 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
      - name: Deploy file to tencent
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'young'   #ssh user name
          server: '${{ secrets.SERVER_HOST }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SERVER_KEY }} #引用之前创建好的secret
          local_path: './*'  # 对应我们项目build的文件夹路径
          remote_path: '/home/nginx/html/blog'